# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/hardkernel/odroidu2/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/hardkernel/odroidu2/proprietary/lib/libMali.so:obj/lib/libMali.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libUMP.so:obj/lib/libUMP.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libion.so:obj/lib/libion.so

PRODUCT_COPY_FILES += \
    vendor/hardkernel/odroidu2/proprietary/bin/iwconfig:system/bin/iwconfig \
    vendor/hardkernel/odroidu2/proprietary/bin/iwlist:system/bin/iwlist \
    vendor/hardkernel/odroidu2/proprietary/usr/idc/odroidu-ts.idc:system/usr/idc/odroidu-ts.idc \
    vendor/hardkernel/odroidu2/proprietary/usr/keylayout/odroidu-ts.kl:system/usr/keylayout/odroidu-ts.kl \
    vendor/hardkernel/odroidu2/proprietary/usr/keylayout/odroidu-ts.kcm:system/usr/keylayout/odroidu-ts.kcm \
    vendor/hardkernel/odroidu2/proprietary/usr/keylayout/odroid-keypad.kl:system/usr/keylayout/odroid-keypad.kl \
    vendor/hardkernel/odroidu2/proprietary/usr/keychars/odroid-keypad.kcm:system/usr/keychars/odroid-keypad.kcm \
    vendor/hardkernel/odroidu2/proprietary/app/ODROID.apk:system/app/ODROID.apk \
    vendor/hardkernel/odroidu2/proprietary/app/DicePlayer_2_0_18.apk:system/app/DicePlayer_2_0_18.apk \
    vendor/hardkernel/odroidu2/proprietary/lib/libSoundTouch.so:system/lib/libSoundTouch.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libdice_ics.so:system/lib/libdice_ics.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libdice_jb.so:system/lib/libdice_jb.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libdice_loadlibrary.so:system/lib/libdice_loadlibrary.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libdice_software.so:system/lib/libdice_software.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libdice_software_ics.so:system/lib/libdice_software_ics.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libdice_software_jb.so:system/lib/libdice_software_jb.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libffmpeg_dice.so:system/lib/libffmpeg_dice.so \
    vendor/hardkernel/odroidu2/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/hardkernel/odroidu2/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/hardkernel/odroidu2/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libUMP.so:system/lib/libUMP.so \
    vendor/hardkernel/odroidu2/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/hardkernel/odroidu2/proprietary/lib/hw/gralloc.odroidu2.so:system/lib/hw/gralloc.odroidu2.so \
    vendor/hardkernel/odroidu2/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/hardkernel/odroidu2/proprietary/vendor/firmware/fimc_is_fw.bin:system/vendor/firmware/fimc_is_fw.bin \
    vendor/hardkernel/odroidu2/proprietary/vendor/firmware/setfile.bin:system/vendor/firmware/setfile.bin \
    vendor/hardkernel/odroidu2/proprietary/vendor/firmware/setfile_S5K3H7.bin:system/vendor/firmware/setfile_S5K3H7.bin
